allow_hosts:
  - ^apptoogoodtogo\.com:443$
  - \.captcha-delivery\.com:443$
  - ^api-sdk\.datadome\.co:443$
command_history: false
ignore_hosts:
  - ^api2\.amplitude\.com:443$
  - ^2jxzjo\.cdn-settings\.appsflyersdk\.com:443$
  - ^sdk\.fra-01\.braze\.eu:443$
  - ^firebase-settings\.crashlytics\.com:443$
  - ^crashlyticsreports-pa\.googleapis\.com:443$
  - ^firebaselogging-pa\.googleapis\.com:443$
  - ^images\.tgtg\.ninja:443$
mode:
  - wireguard
modify_headers:
  - /~q & ~hq X-Android-Cert:/X-Android-Cert/5C4C00B04389BA2BA09860AE3A605C92C74B14CA
scripts:
  - ../tgtg/mitm/scripts/datadome_cookie.py
web_password: '$argon2i$v=19$m=8,t=1,p=1$YWFhYWFhYWE$nXD9kg' # https://github.com/mitmproxy/mitmproxy/issues/7551#issuecomment-2781367454
